#!/usr/bin/env bash
# Get a list of all the processes running on the system.
ps -A -u -h -l -o pid,user,tty,stat,start,time,command | \
# Format the output of ps.
awk '{
  if (NR == 1) {
    print "PID   USER  TTY     STAT  START   TIME COMMAND"
  }
  print $1, $2, $3, $4, $5, $6, $7
}' | \
# Remove the newline character from the end of each line.
sed 's/\n//g' | \
# Sort the output by process ID.
sort -n | \
# Remove duplicate lines from the output.
uniq | \
# Print the first 10 lines of the output.
head -10

